services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    env_file:
      - ../components/database/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../components/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    restart: on-failure
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack
      - ../components/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh:ro
    networks:
      - default
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  mysql_data:
    driver: local
  localstack_data:
    driver: local

networks:
  default:
    driver: bridge
