// Code generated by mockery v2. DO NOT EDIT.

package mocks

import (
	dto "github.com/Ernestgio/Hangout-Planner/services/hangout/internal/dto"
	models "github.com/Ernestgio/Hangout-Planner/services/hangout/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: request
func (_m *MockUserService) CreateUser(request dto.UserCreateRequest) (*models.User, error) {
	ret := _m.Called(request)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(dto.UserCreateRequest) *models.User); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.UserCreateRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
