basePath: /
definitions:
  dto.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.SignUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    type: object
  dto.StandardResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: API documentation for the Hangout Planner service
  title: Hangout Planner API
  version: "1.0"
paths:
  /auth/signin:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT token
      parameters:
      - description: User sign in data
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/dto.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.StandardResponse'
      summary: Sign in
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User sign up data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.StandardResponse'
      summary: Sign up
      tags:
      - auth
swagger: "2.0"
