name: Hangout Service CI

on:
  pull_request:
    paths:
      - "services/hangout/**"

jobs:
  hangout-service-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/hangout

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('services/hangout/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: services/hangout
          args: --timeout=5m ./...

      - name: Run Tests with Coverage
        run: go test -v -coverprofile=coverage.out ./internal/...

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: services/hangout/coverage.out
